### ISSUE TITLE
安装 alibabacloud_dingtalk 模块报错

### ISSUE THREAD

**Issue by mzxc** [aliyun/alibabacloud-python-sdk#31]
# 在查阅钉钉开发文档时, 根据指引, 安装 SDK 报错:

> 文档链接: https://open.dingtalk.com/document/resourcedownload/download-server-sdk

## 命令如下: 

```bash
$ pip install alibabacloud_dingtalk
```

## 错误信息如下:

```text
C:\Users\Administrator>pip install alibabacloud_dingtalk
Collecting alibabacloud_dingtalk
  Using cached alibabacloud_dingtalk-2.1.31-py3-none-any.whl.metadata (3.9 kB)
Collecting alibabacloud-endpoint-util<1.0.0,>=0.0.3 (from alibabacloud_dingtalk)

  Using cached alibabacloud_endpoint_util-0.0.3.tar.gz (2.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-x_trtf1n\ali
babacloud-endpoint-util_bdd8e6aa962741f79bf0350debd8a00c\setup.py", line 33, in
<module>
          VERSION = __import__(PACKAGE).__version__
      ModuleNotFoundError: No module named 'alibabacloud_endpoint_util'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit
h pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\Public\python-3.8.9\python.exe -m pip install
--upgrade pip

C:\Users\Administrator>
```

## 我的解决办法

- 1. 根据错误提示, 去 pypi 下载对应的离线文件包, 手动复制到  site-package 下
- 2. 重新 install, 出现新的依赖报错, 重复步骤 1, 直到安装成功

## 问题

为什么相关的 alibabacloud 前缀依赖不提供 wheel, 这如何让开发者快速开始??????

**Comment by Soulter** [comment]
这个 SDK 甚至连文档都没有，是这个 👍

**Comment by ye4241** [comment]
这竟然是 2024 年的 issue 了啊
